DROP TABLE pedido;

CREATE TABLE pedido
(
	id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	pedido INTEGER NOT NULL,
        dono VARCHAR(50) NOT NULL,
        valor REAL NOT NULL,
	nome VARCHAR(90) NOT NULL,
        atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);